name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: Add a build step here if you need to generate output before deploying

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Directory to publish (e.g., ./dist or ./build)
          publish_branch: gh-pages  # This is the default branch for GitHub Pages deployment
